AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation for VPC'

Resources: 
  MyVPC:
    Types: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '172.16.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags: 
        -Key: BucketName
          Value: MyVPC
